name: Weather Backend

httpCodes:
  success: 200
  created: 201
  noContent: 204
  badRequest: 400
  unauth: 401
  notFound: 404
  conflict: 409
  error: 500

endpoints:
  baseUrl: http://api.openweathermap.org/data/2.5
  location: /location
  current: /weather
  forecast: /forecast